name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Keyattestation"
          path: app/build/outputs/apk/release/*.apk
