name: Android CI

    on:
      push:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Build Release APK
          run: ./gradlew assembleRelease

        - name: Upload APK artifact
          uses: actions/upload-artifact@v4
          with:
            name: my-app-apk
            path: app/build/outputs/apk/release/app-release.apk
